# Fourth Meeting

## NumPy
NumPy (Numerical Python) is an open-source Python library used in nearly every scientific and engineering field. NumPy is the universal standard for working with numerical data in Python and is at the core of the Python scientific and PyData ecosystem.

In [1]:
import numpy as np

## Array

### Creating an Array

In [2]:
#membuat array
a = np.array([1,2,3])
print(a)

#membuat array dari zeros (nol)
b = np.zeros(6)
print(b)

#membuat array dari ones (angka satu)
c = np.ones(6)
print(c)

#membuat random array
d = np.empty(3, order='F')
print(d)

#membuat array dengan batasan
e = np.arange(5,10)
print(e)

[1 2 3]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[5.39948460e-313 2.84327065e-308 1.33360310e+241]
[5 6 7 8 9]


### Add, Remove, and Sort

In [3]:
#menambahkan 2 atau lebih array
print(np.append(e, [1,2]))

#menghapus element dari array menggunakan index
print(np.delete(e, 0))

#menggolongkan array
print(np.sort(e))

[5 6 7 8 9 1 2]
[6 7 8 9]
[5 6 7 8 9]


In [4]:
# multi dimension array
array_example = np.array([
   [   [0,1,2,3],
       [4,5,6,7]],
   [   [0,1,2,3],
       [4,5,6,7]],
   [   [0,1,2,3],
       [4,5,6,7]],
])
array_example = np.array([
    [0,1,2,3],
    [4,5,6,7]])
print(array_example)

[[0 1 2 3]
 [4 5 6 7]]


### Shape and Size

In [5]:
#ndim memberi tahu jumlah axes atau dimensi dari array.
print(array_example.ndim)

#size memberi tahu jumlah total elemen array. 
print(array_example.size)

#shape menampilkan tuple integer yang menunjukkan jumlah elemen yang disimpan di sepanjang setiap dimensi array.
print(array_example.shape)

2
8
(2, 4)


### Reshape

In [6]:
a = np.arange(16)
b = a.reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Convert 1D to 2D

In [7]:
display(a)

#merubah dimensi dengan array yang ada
a2 = a[np.newaxis]
display(a2)
a3 = a2[np.newaxis]
display(a3)

row_vector = a[:,np.newaxis]
row_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [8]:
a = np.arange(5)
display(a)
display(a.shape)

#memperluas array dengan memasukkan axis baru pada posisi yang ditentukan
b = np.expand_dims(a, axis=0)
display(b)
display(b.shape)

array([0, 1, 2, 3, 4])

(5,)

array([[0, 1, 2, 3, 4]])

(1, 5)

### Indexing and Slicing

In [9]:
a

array([0, 1, 2, 3, 4])

In [10]:
print(a[2]) #print elemen ke-3
print(a[:3]) #print dari elemen awal sampai ke-3
print(a[::-2]) #print potongan dari array a yang dimulai dari indeks 0 (elemen pertama) dan melangkah mundur setiap 2 elemen
print(a[::2]) #print potongan dari array a yang dimulai dari indeks 0 (elemen pertama) dan melangkah maju setiap 2 elemen
print(a[-3:]) #print 3 elemen dari belakang.

2
[0 1 2]
[4 2 0]
[0 2 4]
[2 3 4]


In [11]:
array_example

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
#elemen dari array kurang dari sama dengan 5 (slicing dengan ketentuan)
array_example[array_example >= 5]

array([5, 6, 7])

In [13]:
five_up = (array_example >= 5)
array_example[five_up]

array([5, 6, 7])

In [14]:
#elemen dari array yang habis dibagi 2
array_example[array_example%2==0]

array([0, 2, 4, 6])

In [15]:
#slicing menggunakan and
print(array_example[(array_example%2==0) & (array_example > 3)]) #habis dibagi 2 dan lebih dari 3
#slicing menggunakan or
print(array_example[(array_example%2==0) | (array_example > 3)]) #habis dibagi 2 atau lebih dari 3

[4 6]
[0 2 4 5 6 7]


In [16]:
a = np.arange(1,11)
b = a[3:8]
b

array([4, 5, 6, 7, 8])

### Creating Array from Existing Data

In [17]:
a1 = np.array(
   [   [0,1,],
       [4,5,]])
a2 = np.array(
   [   [2,3,],
       [6,7,]])

In [18]:
#stacking vertikal
np.vstack((a1, a2))

array([[0, 1],
       [4, 5],
       [2, 3],
       [6, 7]])

In [19]:
#stacking horizontal
np.hstack((a1, a2))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [20]:
display(a)
a2 = a[np.newaxis]
a4 = np.vstack((a2,a2))
a4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [21]:
#splitting array horizontally
np.hsplit(a4, 5)

[array([[1, 2],
        [1, 2]]),
 array([[3, 4],
        [3, 4]]),
 array([[5, 6],
        [5, 6]]),
 array([[7, 8],
        [7, 8]]),
 array([[ 9, 10],
        [ 9, 10]])]

In [22]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
a = np.arange(3)
b = np.arange(4,7)
print(a)
print(b)

# basic array operations 
print(a + b)
print(a - b)
print(a * b)
print(a / b)

[0 1 2]
[4 5 6]
[4 6 8]
[-4 -4 -4]
[ 0  5 12]
[0.         0.2        0.33333333]


In [26]:
a3

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [27]:
a3.sum()

120

In [28]:
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
#menjumlahkan axis
print(c.sum(axis = 0)) #jumlah tiap baris
print(c.sum(axis = 1)) #jumlah tiap kolom (menyamping)

[15 18 21 24]
[10 26 42]


In [30]:
print(a)
print(a * 1.6)

[0 1 2]
[0.  1.6 3.2]


In [31]:
# error
z = np.array([1,2,'z'])
z * 15

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

### Basic Array Operation

In [ ]:
c

In [ ]:
print(c + c)
print(c - c)
print(c * c)
print(c / c)

### Broadcasting

In [32]:
print(c * 3)
print(c / 2)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]
[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]]


### More Array Operations

In [33]:
print(c.min()) #nilai min
print(c.max()) #nilai max
print(c.sum()) #jumlah element array
print(c.std()) #standar deviasi
print(c.min(axis = 1)) #nilai terkecil dari tiap baris
print(c.max(axis = 0)) #nilai terbesar dari tiap kolom (menyamping)

1
12
78
3.452052529534663
[1 5 9]
[ 9 10 11 12]


## Matrices

### Creating Matrices

In [34]:
z = np.zeros((6,2))
o = np.ones((6,2))
r = np.random.random((6,2))
print(z)
print(o)
print(r)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[0.73159702 0.93970194]
 [0.60548947 0.42897069]
 [0.45298666 0.9882107 ]
 [0.59656252 0.59072132]
 [0.37437389 0.98957725]
 [0.68045351 0.13078398]]


In [35]:
r+o

array([[1.73159702, 1.93970194],
       [1.60548947, 1.42897069],
       [1.45298666, 1.9882107 ],
       [1.59656252, 1.59072132],
       [1.37437389, 1.98957725],
       [1.68045351, 1.13078398]])

In [36]:
a1 = np.array([[0,1],[4,5], [7,8]])
print(a1)
a2 = np.array([[0,1,2],[4,5,6]])
print(a2)

[[0 1]
 [4 5]
 [7 8]]
[[0 1 2]
 [4 5 6]]


In [37]:
np.dot(a1,a2)

array([[ 4,  5,  6],
       [20, 29, 38],
       [32, 47, 62]])

### Matrix Arithmetic

In [38]:
#memotong matriks
a1 = np.array([[1,2],[3,4], [5,6]])
print(a1)
print(a1[0]) #mencetak nilai elemen pertama dari array
print(a1[2]) #mencetak nilai elemen kedua dari array tersebut
print(a1[0:2]) #mencetak elemen dari indeks 0 hingga indeks 1
#mencetak nilai dari elemen yang terletak pada baris pertama (indeks 0) dan kolom kedua (indeks 1)
print(a1[0,1])
print(a1[0][1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[5 6]
[[1 2]
 [3 4]]
2
2


### Transposing and Reshaping

In [39]:
#transforming shape
display(a1)
print(a1.shape)
print(a1.T) #transformasi
print(a1.T.shape)

array([[1, 2],
       [3, 4],
       [5, 6]])

(3, 2)
[[1 3 5]
 [2 4 6]]
(2, 3)


In [40]:
a = np.arange(6)

In [41]:
a2 = a[np.newaxis]
a2.T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [42]:
a3 = a2.reshape(-1,3)
a3

array([[0, 1, 2],
       [3, 4, 5]])

## N-Dimensional Array

### Flatten N-Dimensional Array

In [43]:
# flatten multidimension array into 1D array
a4 = a3.flatten()
print(a4)
print(np.delete(a4, 1))
print(a3)

[0 1 2 3 4 5]
[0 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [44]:
a4 = a3.ravel()
print(a4)
print(np.delete(a4, 1))
print(a3)

[0 1 2 3 4 5]
[0 2 3 4 5]
[[0 1 2]
 [3 4 5]]
